<?php
$I = new FunctionalTester($scenario);
$I->wantTo('perform actions and see result');
$I->amonPage('/');
$I->see('Store');
$I->click('Login');
$I->amonPage('/login');
$I->see('Email');
$I->fillField('email', 'aa@yahoo.com');
$I->fillField('password', '1234');
$I->click('Login');
$I->see('Login');
$I->click('Sign up');
$I->amonPage('/signup');
$I->see('Registration Form');
$I->fillField('first_name', 'hector');
$I->fillField('last_name', 'barrios');
$I->fillField('email', 'hsteveb@yahoo.com');
$I->fillField('password', '1234');
$I->fillField('repassword', '1234');
$I->click('Sign Up');
$I->amonPage('/');
$I->see('Login');
$I->see('Signup');
$I->click('Login');
$I->amonPage('/login');
$I->fillField('email', 'hsteveb@yahoo.com');
$I->fillField('password', '1234');
$I->click('Login');
$I->amonPage('/');
//$I->see('search');
